### ISSUE TITLE
This plugin is blacklisted

### ISSUE THREAD

**Issue by paulfalgout** [mcasimir/gulp-rollup#18]
https://github.com/gulpjs/plugins/blob/master/src/blackList.json#L279

**Comment by Permutatrix** [comment]
[rollup-stream](https://www.npmjs.com/package/rollup-stream) is easier to use with gulp than bare Rollup, if you want to take a look at that as an alternative instead.

**Comment by Permutatrix** [comment]
With gulp-rollup v2, this plugin [has been unblacklisted](https://github.com/gulpjs/plugins/commit/00e1369fb4c66b35a790bf5def77a95415af310c).
