### ISSUE TITLE
Rollup dependency version is too low

### ISSUE THREAD

**Issue by jaywcjlove** [mcasimir/gulp-rollup#25]
Rollup v0.25.4

**Comment by Permutatrix** [comment]
Okay, okay. But you probably shouldn't be using a blacklisted plugin in the first place.

**Comment by jaywcjlove** [comment]
@Permutatrix This is a blacklisted plugin?

**Comment by Permutatrix** [comment]
[Yeah.](https://github.com/mcasimir/gulp-rollup/issues/18) It violates the gulp plugin guidelines and has actually caused [a bit of controversy](https://github.com/mcasimir/gulp-rollup/pull/16) that perfectly demonstrates why those guidelines exist. The "official recommendation" is to use the Rollup module directly, but that's obviously ridiculous, so I made [rollup-stream](https://github.com/Permutatrix/rollup-stream) to replace it. I don't know why they haven't officially recognized rollup-stream's existence, but it's the best way I know of to use Rollup with gulp.

I would really like to deprecate gulp-rollup and redirect users to rollup-stream in the README, but @mcasimir didn't want to do that when I asked him about it, and, you know, it's technically his module.

**Comment by jaywcjlove** [comment]
😄 👌

**Comment by phated** [comment]
@Permutatrix I didn't know about rollup-stream (hard to keep up on everything) but it looks slick.  I'd be interested in you sending a recipe PR to the gulp repo to give it more visibility.

**Comment by Permutatrix** [comment]
@phated Oh, sure thing! When my comment on #18 was ignored I assumed the gulp team saw it and wasn't interested, because I am a child who makes childish assumptions. I suppose I'll put essentially the same code in the recipe that's in the README.
