### ISSUE TITLE
Using the 2.1.0 - error - "Input files must be buffered"

### ISSUE THREAD

**Issue by yairEO** [mcasimir/gulp-rollup#35]
I get this error and had to downgrade to `1.9.0` from `2.1.0`

**Comment by Permutatrix** [comment]
There was a major version number bump, indicating that the API has had a breaking change, so this isn't an issue. Users of the old gulp-rollup should switch to [rollup-stream](https://github.com/gulpjs/gulp/blob/master/docs/recipes/rollup-with-rollup-stream.md), which serves its old purpose.
