### ISSUE TITLE
Error: options.entry must be a string or array of strings!

### ISSUE THREAD

**Issue by lazamar** [mcasimir/gulp-rollup#36]
After I updated from version 1.9.0 to 2.1.0 I began to get the following error.
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: options.entry must be a string or array of strings!
    at /home/marcelo/Programs/reactor/node_modules/gulp-rollup/index.js:34:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by Permutatrix** [comment]
The API has changed&mdash;the major version number bump was to indicate that. The purpose of this plugin is now different, so you'll probably want to switch to [rollup-stream](https://github.com/gulpjs/gulp/blob/master/docs/recipes/rollup-with-rollup-stream.md), which serves its old purpose.

**Comment by lazamar** [comment]
Thanks for that.
