### ISSUE TITLE
"filepath" does not exist in the hypothetical file system!

### ISSUE THREAD

**Issue by rogervila** [mcasimir/gulp-rollup#38]
*This is the [original issue](https://github.com/rollup/rollup/issues/772), but is related with gulp and rollup.*

Hello, I have made a little app in order to test rollup with babel, but I can't import modules. 

I get this message: `"filepath" does not exist in the hypothetical file system!` **but "filepath" does exist**.

This is my `gulpfile.js`

```js
let gulp = require('gulp'),
	runSequence = require('run-sequence'),
	rollup = require('gulp-rollup'),
	rollupIncludePaths = require('rollup-plugin-includepaths'),
	babel = require('rollup-plugin-babel');

gulp.task('default', () => {

	const includePathOptions = {  
		paths: ['src']
	};

	return gulp.src('src/app.js')
		.pipe(rollup({
			entry: './src/app.js',
			sourceMap: 'inline',
			plugins: [
				rollupIncludePaths(includePathOptions),
				babel({
					presets: ['es2015-rollup'],
					babelrc: false
				})
			],
			format: 'umd',
			moduleName: 'testing'
		}))
		.pipe(gulp.dest('dist'));
});
```

What am I missing?

Thank you.

**Comment by rogervila** [comment]
I found the solution [here](https://github.com/rollup/rollup/issues/772#issuecomment-231299803).

**Comment by Permutatrix** [comment]
@rogervila The docs do have information on this, actually. The readme states that for purposes like yours, [rollup-stream](https://github.com/gulpjs/gulp/blob/master/docs/recipes/rollup-with-rollup-stream.md) is more appropriate.

> **Note: This plugin is not appropriate for most use cases,** as it requires every file expected to be imported by Rollup to be loaded into memory preemptively. [rollup-stream](https://github.com/gulpjs/gulp/blob/master/docs/recipes/rollup-with-rollup-stream.md) is preferred for almost all purposes. If you want to transform/synthesize/alias/etc. the files Rollup processes, use Rollup plugins; if there's no Rollup plugin to do what you want, try the gulp-to-Rollup plugin adapter, [rollup-plugin-gulp](https://www.npmjs.com/package/rollup-plugin-gulp). If you really need to synthesize your files in gulp, go ahead and use gulp-rollup&mdash;that's what it's made for.

Here's what it has to say about `options.allowRealFiles`:

> If `options.allowRealFiles` is set to true, gulp-rollup will break the gulp plugin guidelines just for you and allow Rollup to read files directly from the filesystem when a file with a matching name isn't found in the gulp stream. You could use this to weasel your way out of having to use rollup-stream, but that would make you a terrible person.

Your current setup works, but it defeats the purpose of gulp. Plugins aren't supposed to read from the filesystem&mdash;they're supposed to operate on a Vinyl file stream. As for why, it's mostly a philosophical matter. gulp is built on the notion that each tool in the chain can be easy to use, robust, and general-purpose at the same time. For instance, rollup-stream can be used for gulp or for serving Rollup bundles over HTTP or for whatever else you may need a stream for.

So if you find this philosophy appealing, you should use rollup-stream. If you don't, well, do whatever you want. There's nothing inherently wrong with using a screwdriver to pound in a nail. Just remember that that's not its intended purpose, so you may want to use something that aligns more with your methods. Grunt, perhaps.

**Comment by lab-js** [comment]
So, how to avoid this message?

**Comment by Permutatrix** [comment]
@lab-js In most cases, by using rollup-stream instead of gulp-rollup.

**Comment by etranger** [comment]
lab-js, all you need to do is include all the needed files in your `gulp.src()`, which currently only has one file (which is then the only file that ends up in the hypothetical filesystem). no need to change the entry parameter of course.

**Comment by lab-js** [comment]
@etranger, thx so much
