### ISSUE TITLE
Publish update to npm with newest rollup

### ISSUE THREAD

**Issue by danii1** [mcasimir/gulp-rollup#4]
Current npm version uses really outdated rollup version 0.8.3, where external imports doesn't work as they should.

**Comment by mcasimir** [comment]
Thanks going to update now

**Comment by yairEO** [comment]
It's already `0.19.2` and very soon to be `0.20`, I suspect things are moving fast over there.

**Comment by danii1** [comment]
It's, I think it's better to use `latest` for now
```
  "dependencies": {
    "rollup": "latest",
  },
```
I'm closing this issue, thanks @mcasimir for this package :+1:

**Comment by yairEO** [comment]
@danii1 -  why did you close the issue without a commit being made to address this?

Author should change the dependency to `*` then commit and close this automatically

**Comment by Permutatrix** [comment]
We're using David to track out-of-date dependencies now.  This will allow us to follow semver, since Rollup's public API is a part of ours.
