### ISSUE TITLE
how to handle errors?

### ISSUE THREAD

**Issue by yairEO** [mcasimir/gulp-rollup#5]
Seems like when running a normal gulp task, the console is showing everything is ok, and there will be no output bundle file if something wasn't written well in the javascript. for example, I have 2 files:

## entry.js

    import * from './modules';

    console.log( count ); // 0
    increment();
    console.log( count ); // 1

## modules.js

    export var count = 0;
    export function increment () {
      count += 1;
    }

Running this Task will show "bussness as usual" but there will be **no** output file generated

    gulp.task('bundleJS', function() {
        gulp.src('js/dist/test.js', {read: false})
            .pipe(rollup({format: 'amd'}))
            .pipe(gulp.dest('test'))
    });

I would like to know what exactly failed to work.

**Comment by yairEO** [comment]
I see I must use this way of importing - `import * as xxx from './modules';` I didn't know that.. I would think there would be some error in the way I wrote my `import` in `entry.js`

**Comment by Permutatrix** [comment]
Errors are handled properly since 9033417. (I think. I hope...)
