### ISSUE TITLE
json imports cause rollup error

### ISSUE THREAD

**Issue by lexon0011** [mcasimir/gulp-rollup#61]
I use in my angular app following import statements: 

```
import * as currencyData from "cldr-data/supplemental/currencyData.json";
import * as currencies from "cldr-data/main/de/currencies.json";
```

Now I get error during the rollup process. Are there addentinal settings necessary?

Here is the error output and my gulp-rollup config:

[Rollup.zip](https://github.com/mcasimir/gulp-rollup/files/1150194/Rollup.zip)

Thanks!

**Comment by Permutatrix** [comment]
You have to use [rollup-plugin-json](https://www.npmjs.com/package/rollup-plugin-json).

**Comment by lexon0011** [comment]
Works, thanks!
