### ISSUE TITLE
How can I specify a rollup.config.js for rollup?

### ISSUE THREAD

**Issue by LvChengbin** [mcasimir/gulp-rollup#68]
I want to use a config file for rollup, can I do it with gulp-rollup?

**Comment by Permutatrix** [comment]
Not with gulp-rollup. You can do with with [rollup-stream](https://github.com/Permutatrix/rollup-stream#usage-with-rollup-config-file).

I have for a very long time recommended that almost all of gulp-rollup's users switch to rollup-stream.

**Comment by LvChengbin** [comment]
@Permutatrix Thanks a lot.
